config/routes.rb
Rails.application.routes.draw do
  devise_for :users


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root :to => "tops#index"
  resources :lists do
    resources :cards, only: %i(new create show update destroy)
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord

  belongs_to :list

  validates :title, length: { in: 1..255 }
  validates :memo,  length: { maximum: 1000 }
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :cards, dependent: :destroy

  validates :title, length: { in: 1..255 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :lists, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


validates :name, presence: true, length: { maximum: 20 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected


    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    end


    def after_sign_up_path_for(resource)
      user_path(current_user)
    end

    def after_update_path_for(resource)
      user_path(current_user)
    end

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def new
    @card = Card.new
    @list = List.find(params[:list_id])
  end

  def create
    @card = Card.new(card_params)
    @list = List.find(params[:list_id])
    @card.list_id = @list.id
    if @card.save
      redirect_to root_path, notice: "カードを作成しました"
    else
      render action: :new
    end
  end

  def show
    @list = List.find(params[:list_id])
    @lists = List.where(user: current_user)
    @card = Card.find(params[:id])
  end

  def update
    @card = Card.find(params[:id])
    if @card.update(card_params)
      redirect_to root_path, notice: "カード情報を変更しました"
    else
      redirect_to request.referer
      flash[:danger] = "カード情報を変更できませんでした"
    end
  end

  def destroy
    @card = Card.find(params[:id])
    @card.destroy
    redirect_to root_path, notice: "カードを削除しました"
  end

  private
    def card_params
      params.require(:card).permit(:title, :memo, :list_id)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
before_action :authenticate_user!
before_action :set_list, only: %i(edit update)

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.user_id = current_user.id
    if @list.save
      redirect_to root_path
    else
      render action: :new
    end
  end

  def edit
  end

  def destroy
    @list.destroy
    redirect_to :root
  end

  def update
    if @list.update_attributes(list_params)
      redirect_to :root
    else
      render action: :edit
    end
  end

private
#mergeメソッドは2つのハッシュを統合するメソッドです。今回は誰がリストを作成したかという情報がほしいため。
#これにより、@list.user_id = current_user.idの記述が省略できる。すでに誰がリストを作成した情報を載せているため。
  def list_params
    params.require(:list).permit(:title)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  before_action :authenticate_user!

  def index
    @lists = List.where(user: current_user).order("created_at ASC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/cards/new.html.erb
<div class="container-md shadow-lg p-3">
  <%= render "shared/flash_message" %>
  <div class='row'>
    <div class="col-sm-10 col-md-8 col-lg-6 col-xl-5 mx-auto text-dark">
      <h2 class="mb-3 ml-sm-n2 text-center">New Card</h2>
      <%= form_with model: @card, url: { action: :create }, local: true do |f| %>
        <div class="col-md-12">
          <div class="form-group row">
            <h3 class="col-form-label">題名</h3>
            <%= f.text_field :title, placeholder: "カード名を記述して下さい", class: 'form-control' %>
          </div>
          <div class="form-group row">
            <h3 class="col-form-label">詳細</h3>
            <%= f.text_area :memo, placeholder: "詳細を記述して下さい", :size => "60x10",class: 'form-control' %>
          </div>
          <div class="form-group row">
            <%= f.submit class: 'btn btn-secondary form-control btn-outline-light  hover-img' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cards/show.html.erb
<% content_for :title, "投稿詳細" %>
  <div class="container shadow-lg p-3">
    <div class="col-sm-4 mx-auto text-center"><%= render "shared/flash_message" %></div>
    <div class="row">
      <div class="col-md-8 mx-auto mt-2">
        <div class="card h-100 border-0 bg-transparent text-dark">
          <div class="card-body">
            <p class="card-text border-bottom">題名：<%= @card.title %></p>
            <p class="card-text border-bottom">本文：<%= @card.memo %></p>
          </div>
          <div class="card-footer bg-transparent border-0 pt-0 d-flex">
            <div class="flex-grow-1">

               <span>
                  <span class="hover-img m-1 fa-2x  text-decoration-none" data-toggle="modal" data-target="#modal1">
                    <i class="far fa-edit modal-fullscreen-xl-down hover-img"></i>
                  </span>
                  <%= link_to list_card_path(@list, @card), method: :delete, data: { confirm: "本当に投稿を消しますか？" }, class: "hover-img m-1 fa-2x text-reset text-decoration-none" do %>
                   <i class="far fa-trash-alt"></i>
                  <% end %>
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

<!--モーダルウィンドウの記述-->
<div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="label1" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content bg-transparent">
      <div class="modal-header">
        <h5 class="modal-title text-white" id="label1">投稿の編集</h5>
        <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render "shared/card_edit", lists: @lists, card: @card %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-transparent hover-img text-white" data-dismiss="modal">閉じる</button>
      </div>
    </div>
  </div>
</div>
<!--モーダルウィンドウの記述ここまで-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kanban</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

        <%# ここに追加する %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="top_padding">

   <header class="header">
    <%= render "shared/header" %>
   </header>

    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
 <div class="container-md shadow-lg p-3">
    <%= render "shared/flash_message" %>
    <div class='row'>
      <div class="col-sm-10 col-md-8 col-lg-6 col-xl-5 mx-auto text-dark">
        <h2 class="mb-3 ml-sm-n2 text-center">Edit Task</h2>
        <%= form_with model: @list, local: true do |f| %>
          <div class="col-md-12">
            <div class="form-group row">
              <h3 class="col-form-label">題名</h3>
              <%= f.text_field :title, placeholder: "題名を記述して下さい", class: 'form-control' %>
            </div>
            <div class="form-group row">
              <%= f.submit class: 'btn btn-secondary form-control btn-outline-light  hover-img' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/lists/new.html.erb
 <div class="container-md shadow-lg p-3">
    <%= render "shared/flash_message" %>
    <div class='row'>
      <div class="col-sm-10 col-md-8 col-lg-6 col-xl-5 mx-auto text-dark">
        <h2 class="mb-3 ml-sm-n2 text-center">New Task</h2>
        <%= form_with model: @list, local: true do |f| %>
          <div class="col-md-12">
            <div class="form-group row">
              <h3 class="col-form-label">題名</h3>
              <%= f.text_field :title, placeholder: "題名を記述して下さい", class: 'form-control' %>
            </div>
            <div class="form-group row">
              <%= f.submit class: 'btn btn-secondary form-control btn-outline-light  hover-img' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/shared/_card_edit.html.erb
<div class="container-md shadow-lg p-3">
  <%= render "shared/flash_message" %>
  <div class='row'>
    <div class="col-sm-10 col-md-8 col-lg-6 col-xl-5 mx-auto text-dark">
      <h2 class="mb-3 ml-sm-n2 text-center">Edit Card</h2>
      <%= form_with model: card, url: { action: :update }, local: true do |f| %>
        <div class="col-md-12">
          <div class="form-group row">
            <h3 class="col-form-label">題名</h3>
            <%= f.text_field :title, placeholder: "カード名を記述して下さい", class: 'form-control' %>
          </div>
          <div class="form-group row">
            <h3 class="col-form-label">詳細</h3>
            <%= f.text_area :memo, placeholder: "詳細を記述して下さい", :size => "60x10",class: 'form-control' %>
          </div>
          <div class="form-group row">
            <h3 class="col-form-label">リスト名</h3>
            <%= select :card, :list_id, lists.map{ |l| [l.title, l.id] }, {}, { class: 'form-control' } %>
          </div>
          <div class="form-group row">
            <%= f.submit class: 'btn btn-secondary form-control btn-outline-light  hover-img' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <% alert_type = message_type == "notice" ? "success" : "danger" %>
  <div class="alert alert-<%= alert_type %> alert-dismissible fade show" >
    <%= message %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_form_error.html.erb
	<%# フォームエラー表示の共通レイアウト %>
<%# 引数にformのmodelを指定 %>
<% if model.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show">
    <h5 class="alert-heading">
      <%= model.errors.count %> 件修正して下さい:
    </h5>
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_header.html.erb
    <nav class="navbar navbar-dark fixed-top navbar-expand-lg bg-dark">
      <div class="container-fluid">

        <!-- ハンバーガーメニュー -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
        </button>
        <!-- ナビゲーションメニュー -->
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">

            <!--ユーザー側のヘッダー-->
            <% if user_signed_in? %>
              <% # userサインイン済 %>
              <li class="nav-item">
                <%= link_to "ホーム", root_path, class: "nav-link hover-img text-white" %>
              </li>
              <li class="nav-item">
                <%= link_to "リストを作成", new_list_path, class: "nav-link hover-img text-white" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link hover-img text-white" %>
              </li>
            <% else %>
            <ul class="navbar-nav">
                <% # userサインイン前 %>
              <li class="nav-item">
                <%= link_to "ホーム", root_path, class: "nav-link hover-img text-white" %>
              </li>
              <li class="nav-item active">
                <%= link_to "ログイン",  new_user_session_path, class: "nav-link hover-img text-white mr-2" %>
              </li>
              <li class="nav-item active">
                <%= link_to "新規登録",  new_user_registration_path, class: "nav-link hover-img text-white mr-2" %>
              </li>
            </ul>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

app/views/tops/index.html.erb
  <div class="container-fluid p-3 ">
    <div class="col-sm-4 mx-auto text-center"><%= render "shared/flash_message" %></div>
    <h3 class="text-dark font-italic text-center m-4">タスク管理</h3>
    <div class='row mx-auto fadeUp'>
      <% @lists.each do |list| %>
        <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6">
          <div class="mb-4 card-deck">
            <div class="card text-white border-dark mb-3 bg-dark" >
              <h3 class="card-title font-weight-bold text-center m-1"><%= list.title %></h3>
              <span class="text-right mr-3">
                <%= link_to edit_list_path(current_user.id), class: "hover-img m-1 fa-2x text-reset text-decoration-none" do %>
                 <i class="far fa-edit modal-fullscreen-xl-down hover-img"></i>
                <% end %>
                <%= link_to list_path(current_user.id), method: :delete, data: { confirm: "本当に投稿を消しますか？" }, class: "hover-img m-1 fa-2x text-reset text-decoration-none" do %>
                 <i class="far fa-trash-alt"></i>
                <% end %>
              </span>
              <div class="card-body">
              <% list.cards.each do |card| %>
                <div class="card m-2 text-dark">
                <%= link_to list_card_path(list.id, card.id), class: "m-1 text-reset text-decoration-none" do %>
                  <h5 class="card_title"><%= card.title %></h5>
                  <% if card.memo.size > 0 %>
                    <div class="card_detail is-exist"><i class="fas fa-bars"></i></div>
                  <% end %>
                <% end %>
                </div>
              <% end %>
              </div>
              <div class="card-body">
                <i class="far fa-plus-square"></i>
                <%= link_to "さらにカードを追加", new_list_card_path(list), class: "addCard_link" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>